import { Button, Group } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = (props) => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Group>
        <Button>Button</Button>
      </Group>
    </>
  );
};

export default Home;